import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import yaml from "js-yaml";
import { workspaceMap } from "@/lib/anythingllm";

type SyncEntry = { hash: string; workspace: string; location?: string; syncedAt?: string; status: "success" | "failed"; error?: string };
type SyncState = { lastSync?: string; files: Record<string, SyncEntry> };
const root = process.cwd(), contentRoot = path.join(root, "content"), stateFile = path.join(root, "data", "sync-state.json");
function files(dir: string): string[] { return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>{const target=path.join(dir,e.name);return e.isDirectory()?files(target):(/\.md$/i.test(e.name)?[target]:[]);}); }
function currentFiles(){return files(contentRoot).map(file=>{const raw=fs.readFileSync(file,"utf8");const header=raw.match(/^---\r?\n([\s\S]*?)\r?\n---/)?.[1];if(!header)throw new Error(`${path.relative(contentRoot,file)} 缺少 YAML 元数据`);const metadata=yaml.load(header) as Record<string,unknown>;return{file,raw,relativePath:path.relative(contentRoot,file).replaceAll(path.sep,"/"),workspace:String(metadata.workspace||""),title:String(metadata.title||""),hash:crypto.createHash("sha256").update(raw).digest("hex")};});}
export function readState():SyncState{if(!fs.existsSync(stateFile))return{files:{}};try{return JSON.parse(fs.readFileSync(stateFile,"utf8"));}catch{return{files:{}};}}
export function previewSync(){const state=readState(),current=currentFiles(),names=new Set(current.map(f=>f.relativePath));return{lastSync:state.lastSync,total:current.length,added:current.filter(f=>!state.files[f.relativePath]).map(f=>({path:f.relativePath,title:f.title,workspace:f.workspace})),modified:current.filter(f=>state.files[f.relativePath]&&state.files[f.relativePath].hash!==f.hash).map(f=>({path:f.relativePath,title:f.title,workspace:f.workspace})),unchanged:current.filter(f=>state.files[f.relativePath]?.hash===f.hash).length,pendingDeletion:Object.keys(state.files).filter(f=>!names.has(f)),failed:Object.entries(state.files).filter(([,v])=>v.status==="failed").map(([file,v])=>({path:file,error:v.error}))};}
async function upload(base:string,key:string,file:ReturnType<typeof currentFiles>[number]){const form=new FormData();form.append("file",new Blob([file.raw],{type:"text/markdown"}),path.basename(file.file));const res=await fetch(`${base}/api/v1/document/upload`,{method:"POST",headers:{Authorization:`Bearer ${key}`},body:form});if(!res.ok)throw new Error(`上传失败 (${res.status}): ${await res.text()}`);const result=await res.json();const location=result.documents?.[0]?.location||result.document?.location||result.location;if(!location)throw new Error("AnythingLLM 未返回 document location");return String(location);}
async function embed(base:string,key:string,slug:string,adds:string[],deletes:string[]){const res=await fetch(`${base}/api/v1/workspace/${encodeURIComponent(slug)}/update-embeddings`,{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({adds,deletes})});if(!res.ok)throw new Error(`Workspace 嵌入失败 (${res.status}): ${await res.text()}`);}
export async function executeSync(){const base=process.env.ANYTHINGLLM_BASE_URL?.replace(/\/$/,""),key=process.env.ANYTHINGLLM_API_KEY;if(!base||!key)throw new Error("未配置 AnythingLLM 连接信息");const mapping=workspaceMap(),state=readState(),changed=currentFiles().filter(f=>state.files[f.relativePath]?.hash!==f.hash),results=[];for(const file of changed){try{const slug=mapping[file.workspace];if(!slug)throw new Error(`缺少“${file.workspace}”Workspace 映射`);const old=state.files[file.relativePath],location=await upload(base,key,file);await embed(base,key,slug,[location],old?.location?[old.location]:[]);state.files[file.relativePath]={hash:file.hash,workspace:file.workspace,location,syncedAt:new Date().toISOString(),status:"success"};results.push({path:file.relativePath,status:"success"});}catch(error){state.files[file.relativePath]={hash:file.hash,workspace:file.workspace,status:"failed",error:error instanceof Error?error.message:String(error)};results.push({path:file.relativePath,status:"failed",error:state.files[file.relativePath].error});}}state.lastSync=new Date().toISOString();fs.writeFileSync(stateFile,JSON.stringify(state,null,2)+"\n");return{results,preview:previewSync()};}
